### ISSUE TITLE
Partial files

### ISSUE THREAD

**Issue by JudeOsborn** [edm00se/modernize-ng1#169]
Did you ever find a solution to using html files for partial (instead of embedding partials in script tags)?

Main issue I'm having is that the directive's link parameter has no knowledge of parcel's unique naming scheme.

**Comment by edm00se** [comment]
I wound up pulling in the HTML for the `template`, as opposed to using `templateUrl`, via the `require` syntax. Parcel (v1, out of the box) can `require` html assets directly so this made things far easier than some other alternatives.

https://github.com/edm00se/modernize-ng1/blob/master/src/js/app.js#L23-L27

**Comment by JudeOsborn** [comment]
Interesting. I've been having trouble with this with both parcel 1 and 2. In both cases the HTML files return an empty string. I've tried using import instead but get an error about the file starting in "<". Do you require any special libraries? Babel for example?

**Comment by JudeOsborn** [comment]
Strangely enough I cloned your project and imported my files (rather than adapting yours) and now require is working fine with html files. No idea what I was doing wrong, but all good now. Thanks for the repo. Extremely helpful.

**Comment by edm00se** [comment]
I’ve not gotten it to work in parcel 2 yet, I’m guessing it’ll need a dedicated plugin. I’ve also not checked into it in a little while. I’m glad you were able to get things working with the repo, cheers.
