### ISSUE TITLE
Update Angular Dependencies

### ISSUE THREAD

**Issue by edm00se** [edm00se/modernize-ng1#7]
Currently, the `angular` dependency and its peers (those from Google and the AngularJS package ecosystem) are still on 1.7.4. They should be updated to the latest, which is 1.7.5.

There is a `package-lock.json` file at play, so cloning the repository and installing them should be done for proper updating of the lock file.

**Comment by WillKoenig** [comment]
Hey I'd love to take care of this.

**Comment by edm00se** [comment]
To ensure things are nice and clear, this issue has been claimed by @WillKoenig. If I don't see a PR in what I deem to be a reasonable time period, I'll consider this up for grabs. Thanks all.

**Comment by edm00se** [comment]
Closed  by #9.
